[tool.poetry]
name = "generic"
version = "1.0.0"
description = "Generic programming library for Python"
authors = [
    "Andrey Popp <8mayday@gmail.com>",
    "Arjan Molenaar <gaphor@gmail.com>"
]
maintainers = [
    "Arjan Molenaar <gaphor@gmail.com>",
    "Dan Yeaw <dan@yeaw.me>"
]

license = "BSD License"
readme = "README.md"
homepage = "https://generic.readthedocs.io/"
repository = "https://github.com/gaphor/generic"
documentation = "https://generic.readthedocs.io/"

keywords = ["generic", "multi dispatch", "dispatch", "event"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.10"
pytest-runner = "^5.1"
black = { version = "^20.8b1", python = "^3.7" }
mypy = "0.782"
pre-commit = "^2.7"
bw_sphinxtheme = "^0.1.8"
tox = "^3.20"

[build-system]
requires = ["poetry>=1.0.0b3"]
build-backend = "poetry.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py37, py38

[testenv]
whitelist_externals =
    poetry
    xvfb-run
skip_install = true
commands =
    poetry install -v
    xvfb-run -a pytest
"""

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = ["pytest"]
skip = ".venv,build,dist"
