name: build

env:
  POETRY_VERSION: 1.1.3

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v2.1.3
      - name: Lint with Pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.1.3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry==$POETRY_VERSION
      - name: Install Python Dependencies
        run: poetry install
      - name: Test with Pytest
        run: xvfb-run pytest
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: f9441442730130d385df69241a779ac3b663756ed21881179826e3fab7e01924
        with:
          coverageCommand: coverage xml
